### ISSUE TITLE
command "rmt" removes too much

### ISSUE THREAD

**Issue by LucasBornhauser** [gyselroth/docxbox#13]
**Describe the bug**
When running the "rem" command more than the expected strings are removed. 

**To Reproduce**
1. Command: "./docxbox rem test/files/docx/cp_table_unordered_list_images.docx Dolore incididunt
2. Resources: copy of table_unordered_list_images.docx

**Expected behavior**
All strings in between and including given strings are removed from given .docx

**Screenshots**
Original docx: 
![Auswahl_048](https://user-images.githubusercontent.com/32673972/79981105-660f4080-84a4-11ea-86fc-435bd58c37a7.png)

Manipulated docx: 
![Auswahl_047](https://user-images.githubusercontent.com/32673972/79981141-732c2f80-84a4-11ea-9f25-0cd98f642b26.png)

**Environment:**
 - docxBox Version: 0.0.2

**Comment by kstenschke** [comment]
> Expected behavior
> All strings in between and including given strings are removed from given .docx

"rem" ATM removes not strings, but content - that is: all word xml nodes including those containing  given left- and right-hand-side strings, and inbetween. TBD: add option / argument for textual removal or removal of specific elements (e.g. parent paragraph, table row, etc.)
