### ISSUE TITLE
command "lorem" doesn't replace text and throws an error

### ISSUE THREAD

**Issue by LucasBornhauser** [gyselroth/docxbox#31]
**Describe the bug**
When trying to randomize text in a docx file by running "docxbox lorem .docx" an error is thrown: 

**terminate called after throwing an instance of 'std::logic_error' 
what():  basic_string::_M_construct null not valid**

**To Reproduce**
1. Command: docxbox lorem
2. Resources: any valid docx

**Expected behavior**
Text in provided docx file gets replaced by random text

**Environment:**
 - docxBox Version: 0.0.4

**Comment by kstenschke** [comment]
lorem was removing the source docx, see https://github.com/gyselroth/docxbox/commit/baf9a3dfda144ee4bcdd6fa6b634c0211702f81d
