### ISSUE TITLE
use word2016 can not open bio_assay.docx in test file

### ISSUE THREAD

**Issue by redrose007** [gyselroth/docxbox#38]
**Describe the bug**
replace text using markup text, then the docx file can not be open by word2016 

**To Reproduce**
1. Command ' ./docxbox rpt /mnt/hgfs/vmware-share/docxbox-master/docxbox-master/test/files/docx/mergefields.docx sunt "{\"h1\":{\"text\":\"Foo\"}}" '

**Environment:**
 - docxBox Version:newest
 - DOCX Processor, if involved (Microsoft Word or other application)

**Comment by kstenschke** [comment]
Thank you @redrose007 for contributing to the docxBox project! :+1:

We are currently implementing the basis, so we can reach a substantial comprehensive level of flexible templating hopefully soon. 

I want to reassure you that, as stated in the [roadmap](https://github.com/gyselroth/docxbox#roadmap), ensuring full Microsoft Word compatibility will be one major focal point of the second-next release (0.0.6).

Thank you once again for your input, please feel encouraged to let us know your observations while testing out docxBox. Your outside perspective is greatly appreciated.

**Comment by kstenschke** [comment]
Issue was caused by incompatible input file: all test DOCX have been corrected now.
Please feel free to recheck and let us know in case of further issues.
