### ISSUE TITLE
error in "mm" command

### ISSUE THREAD

**Issue by LucasBornhauser** [gyselroth/docxbox#43]
**Describe the bug**
Trying to change the meta attribute "subject" throws an error: 
**`"terminate called after throwing an instance of 'char const*'"`**

**To Reproduce**
1. Command: ./docxbox mm file.docx subject "replacementString" 
2. Resources: any valid docx file containing the meta attribute "subject"

**Expected behavior**
Meta attribute gets changed 

**Environment:**
 - docxBox Version: 0.0.5

**Comment by kstenschke** [comment]
Resolved with revision 630fa6b1ccc96a5cff162b6b32b6b892dcdc23ad
