### ISSUE TITLE
Feature: Add valgrind memory-leak test

### ISSUE THREAD

**Issue by kstenschke** [gyselroth/docxbox#65]
* allow test.sh to receive optional argument: "valgrind"
* when running in valgrind mode: add bats-preparation for executing test-suite w/ valgrind: copy functional-suites, replace doxbox binary-path within all copied suites prefixed w/ valgrind execution
* test leak detection and reporting: provoke leakage, ensure correct error-message and return-signal

**Comment by LucasBornhauser** [comment]
Closed with PR #79

**Comment by kstenschke** [comment]
👍
