### ISSUE TITLE
Replacing an image without providing a replacement image creates a folder in project root

### ISSUE THREAD

**Issue by LucasBornhauser** [gyselroth/docxbox#8]
**Describe the bug**
Trying to replace an image omitting the image- name and path to be replaced, a folder containing the files of the given .docx named like the .docx file is created in the project root. 
An error message is given, stating a file name of the replacement image is missing. 

**To Reproduce**
Command:

-  $ ./bin/linux/docxbox rpi test/files/table_unordered_list_images.docx image1.jpeg

Files: 

- table_unordered_list_images.docx

**Expected behavior**
An error message. 

**Environment:**
 - docxBox Version: 0.0.1

**Comment by kstenschke** [comment]
![Auswahl_044](https://user-images.githubusercontent.com/1838456/79501445-57e99c00-802e-11ea-86b0-174e96da9c70.png)
